"""add_receiving_table

Revision ID: 619aa8dfa603
Revises: 8e23cdaf3a9e
Create Date: 2021-07-21 08:30:54.535463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619aa8dfa603'
down_revision = '8e23cdaf3a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receiving',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('Item_Type_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('isCommitted', sa.Boolean(), nullable=True),
    sa.Column('item', sa.String(length=50), nullable=False),
    sa.Column('purchase_price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['Item_Type_id'], ['item_types.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receiving')
    # ### end Alembic commands ###
