"""PlayerChanges

Revision ID: b27738eaa89e
Revises: 82c076493146
Create Date: 2021-02-27 19:45:41.117244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27738eaa89e'
down_revision = '82c076493146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'email')
    # ### end Alembic commands ###
